# Generated by Django 3.2.8 on 2021-10-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_post', models.CharField(max_length=120)),
                ('text_post', models.TextField()),
                ('date_post', models.DateTimeField()),
                ('image', models.ImageField(upload_to='event_images/')),
            ],
        ),
    ]
